### ISSUE TITLE
[BUG]: "Great On Deck" library tab is gone after installing Tab Master.

### ISSUE THREAD

**Issue by TorinoFermic** [Tormak9970/TabMaster#214]
**Describe the bug**
In library of my Steam Deck, the original tab "Great On Deck" has vanished when I install Tab Master. Looking in their settings shows this tab isn't hidden.

**To Reproduce**
1. Start installing Tab Master with Decky Loader
2. Go to Library and check all tabs for any missing tabs like "Great On Deck"
3. "Great On Deck" is gone

**Expected behavior**
The tab "Great On Deck" should be present among Steam original tabs.

**Screenshots**
![20240920173325_1](https://github.com/user-attachments/assets/73c3d266-e42a-40c7-8a62-e20aa6225207)
![20240920173654_1](https://github.com/user-attachments/assets/150d5732-6339-4725-9482-1834f33e1860)

**Logs**:
[2024-09-20 20.05.16.log](https://github.com/user-attachments/files/17081782/2024-09-20.20.05.16.log)

**Enviroment Info:**
 - SteamOS Version 3.5.19
 - SteamOS Update Channel Stable
 - Decky Version 3.0.0
 - Decky Update Channel Stable
 - TabMaster Version 2.7.0

**Comment by Tormak9970** [comment]
Valve changed the tab's id. Fixed as of https://github.com/Tormak9970/TabMaster/commit/a5fed02094ba09108128f7ed9a6dd37edb9f5949. Will get a new release built soon

**Comment by parseddiopter** [comment]
Glad I was able to find this! I thought I broke something 😁

**Comment by COD3THR33** [comment]
Noticed this was reported for 2.7.0

Still experiencing this issue in 2.7.2 — was this supposed to be already fixed in 2.7.2 or in the next release?

Thx!

**Comment by jessebofill** [comment]
> Noticed this was reported for 2.7.0
> 
> Still experiencing this issue in 2.7.2 — was this supposed to be already fixed in 2.7.2 or in the next release?
> 
> Thx!

I think we still need to make a new release and submit it to the store.

**Comment by jessebofill** [comment]
More specifically there was still an outstanding case this would occur that has since been fixed but not released.
